songbird-server
Oleg11713/songbird-server pull request #1
Opened 2022-01-25 19:10 UTC by Oleg11713

2022-01-27 09:12 UTC, VladislavTemriuk requested changes
Need some changes

2022-01-27 09:22 UTC, Oleg11713 commented on controllers/gameController.js
> +    let { id, name, species, description, image, audio } = req.body;
Replaced let with const

2022-01-27 09:27 UTC, Oleg11713 commented on controllers/userController.js
> +const ApiError = require("../error/ApiError");
Grouped all imports (first from node_modules, then my own files)

2022-01-27 09:33 UTC, Oleg11713 commented on controllers/userController.js
> +    const hashPassword = await bcrypt.hash(password, 5);
Made a constant SALT and renamed the "hashPassword" to "passwordHash" for better understanding

2022-01-27 09:36 UTC, Oleg11713 commented on controllers/userController.js
> +  async check(req, res, next) {
Initially, I wanted to make an additional token verification function, but later I decided that I didn’t need it, and forgot to remove it
I also didn't need the function getAll in userController
Removed unused features

2022-01-27 09:40 UTC, Oleg11713 commented on db.js
> +);
Done

2022-01-27 09:44 UTC, Oleg11713 commented on models/models.js
> +});
Separated models into files userModel and birdModel

2022-01-27 09:50 UTC, Oleg11713 commented on routes/index.js
> +router.use("/", gameRouter);
Done

2022-01-27 11:28 UTC, Oleg11713 commented on .env.example
> +SECRET_KEY
Renamed to ACCESS_TOKEN_KEY

2022-01-27 11:43 UTC, Oleg11713 commented on controllers/userController.js
> +  async check(req, res, next) {
The function checks the token, if it does not exist, the middlewareAuth gives an error 401, I forgot to write the function in the client, I have already added it
Also removed unused function getAll in userController

2022-01-27 12:29 UTC, Oleg11713 commented on controllers/userController.js
> +    const { displayName, email, password, totalScoreForAllGames } = req.body;
Done

2022-01-28 07:28 UTC, VladislavTemriuk requested changes
Good job

but need some changes

2022-01-28 07:28 UTC, VladislavTemriuk commented on middleware/authMiddleware.js
> +    req.user = jwt.verify(token, process.env.ACCESS_TOKEN_KEY);
you should check if token didn't pass a verification

2022-01-28 07:28 UTC, VladislavTemriuk commented on routes/gameRouter.js
> +router.patch("/", userController.updateTotalScore);
maybe also add path for this route? for example `/updateScore`

2022-01-28 07:28 UTC, VladislavTemriuk commented on routes/gameRouter.js
> +router.patch("/", userController.updateTotalScore);
also you should add middleware for this routes, because without it everyone can call it and change data

2022-01-28 09:17 UTC, Oleg11713 commented on controllers/gameController.js
> +  }
Initially, I created a function to check whether requests are working correctly, now it is really not needed (removed)

2022-01-28 09:20 UTC, Oleg11713 commented on controllers/gameController.js
> +class GameController {
Looked again, really wrong name (renamed)

2022-01-28 09:22 UTC, Oleg11713 commented on controllers/userController.js
> +    const comparePassword = await bcrypt.compareSync(password, user.password);
Corrected

2022-01-28 09:45 UTC, Oleg11713 commented on middleware/authMiddleware.js
> +    req.user = jwt.verify(token, process.env.ACCESS_TOKEN_KEY);
Done

2022-01-28 09:46 UTC, Oleg11713 commented on routes/gameRouter.js
> +router.patch("/", userController.updateTotalScore);
Added path for route ('/updateScore')

2022-01-29 16:12 UTC, Oleg11713 commented on routes/gameRouter.js
> +router.patch("/", userController.updateTotalScore);
Added middleware for this route to check who is trying to change

2022-01-31 20:35 UTC, VladislavTemriuk requested changes
Good job👍

2022-01-31 20:35 UTC, VladislavTemriuk commented on routes/userRouter.js
> +  checkForUpdateMiddleware,
i'm not sure that you check for update, you check if user is authorised. So better to name it authMiddleware

2022-01-31 20:35 UTC, VladislavTemriuk commented on routes/userRouter.js
> +  checkForUpdateMiddleware,
and you have almost the same middleware's, just with different error messages and statuses, so if you need them both, better to pass arguments to not duplicate the code

2022-09-25 10:40 UTC, closed without merging